services:
  db:
    image: postgres:15
    container_name: mc_wiki_postgres
    restart: always
    environment:
      POSTGRES_USER: wiki_user
      POSTGRES_PASSWORD: wiki_password
      POSTGRES_DB: mc_wiki
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
