/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KindIndexRouteImport } from './routes/$kind.index'
import { Route as EditorTabsRouteImport } from './routes/editor.tabs'
import { Route as EditorRecipesRouteImport } from './routes/editor.recipes'
import { Route as KindSlugRouteImport } from './routes/$kind.$slug'
import { Route as EditorTabsIdRouteImport } from './routes/editor.tabs.$id'
import { Route as EditorRecipesIdRouteImport } from './routes/editor.recipes.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KindIndexRoute = KindIndexRouteImport.update({
  id: '/$kind/',
  path: '/$kind/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorTabsRoute = EditorTabsRouteImport.update({
  id: '/tabs',
  path: '/tabs',
  getParentRoute: () => EditorRoute,
} as any)
const EditorRecipesRoute = EditorRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => EditorRoute,
} as any)
const KindSlugRoute = KindSlugRouteImport.update({
  id: '/$kind/$slug',
  path: '/$kind/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorTabsIdRoute = EditorTabsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EditorTabsRoute,
} as any)
const EditorRecipesIdRoute = EditorRecipesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EditorRecipesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRouteWithChildren
  '/search': typeof SearchRoute
  '/$kind/$slug': typeof KindSlugRoute
  '/editor/recipes': typeof EditorRecipesRouteWithChildren
  '/editor/tabs': typeof EditorTabsRouteWithChildren
  '/$kind/': typeof KindIndexRoute
  '/editor/recipes/$id': typeof EditorRecipesIdRoute
  '/editor/tabs/$id': typeof EditorTabsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRouteWithChildren
  '/search': typeof SearchRoute
  '/$kind/$slug': typeof KindSlugRoute
  '/editor/recipes': typeof EditorRecipesRouteWithChildren
  '/editor/tabs': typeof EditorTabsRouteWithChildren
  '/$kind': typeof KindIndexRoute
  '/editor/recipes/$id': typeof EditorRecipesIdRoute
  '/editor/tabs/$id': typeof EditorTabsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRouteWithChildren
  '/search': typeof SearchRoute
  '/$kind/$slug': typeof KindSlugRoute
  '/editor/recipes': typeof EditorRecipesRouteWithChildren
  '/editor/tabs': typeof EditorTabsRouteWithChildren
  '/$kind/': typeof KindIndexRoute
  '/editor/recipes/$id': typeof EditorRecipesIdRoute
  '/editor/tabs/$id': typeof EditorTabsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/editor'
    | '/search'
    | '/$kind/$slug'
    | '/editor/recipes'
    | '/editor/tabs'
    | '/$kind/'
    | '/editor/recipes/$id'
    | '/editor/tabs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/editor'
    | '/search'
    | '/$kind/$slug'
    | '/editor/recipes'
    | '/editor/tabs'
    | '/$kind'
    | '/editor/recipes/$id'
    | '/editor/tabs/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/editor'
    | '/search'
    | '/$kind/$slug'
    | '/editor/recipes'
    | '/editor/tabs'
    | '/$kind/'
    | '/editor/recipes/$id'
    | '/editor/tabs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  EditorRoute: typeof EditorRouteWithChildren
  SearchRoute: typeof SearchRoute
  KindSlugRoute: typeof KindSlugRoute
  KindIndexRoute: typeof KindIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$kind/': {
      id: '/$kind/'
      path: '/$kind'
      fullPath: '/$kind/'
      preLoaderRoute: typeof KindIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/tabs': {
      id: '/editor/tabs'
      path: '/tabs'
      fullPath: '/editor/tabs'
      preLoaderRoute: typeof EditorTabsRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/recipes': {
      id: '/editor/recipes'
      path: '/recipes'
      fullPath: '/editor/recipes'
      preLoaderRoute: typeof EditorRecipesRouteImport
      parentRoute: typeof EditorRoute
    }
    '/$kind/$slug': {
      id: '/$kind/$slug'
      path: '/$kind/$slug'
      fullPath: '/$kind/$slug'
      preLoaderRoute: typeof KindSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/tabs/$id': {
      id: '/editor/tabs/$id'
      path: '/$id'
      fullPath: '/editor/tabs/$id'
      preLoaderRoute: typeof EditorTabsIdRouteImport
      parentRoute: typeof EditorTabsRoute
    }
    '/editor/recipes/$id': {
      id: '/editor/recipes/$id'
      path: '/$id'
      fullPath: '/editor/recipes/$id'
      preLoaderRoute: typeof EditorRecipesIdRouteImport
      parentRoute: typeof EditorRecipesRoute
    }
  }
}

interface EditorRecipesRouteChildren {
  EditorRecipesIdRoute: typeof EditorRecipesIdRoute
}

const EditorRecipesRouteChildren: EditorRecipesRouteChildren = {
  EditorRecipesIdRoute: EditorRecipesIdRoute,
}

const EditorRecipesRouteWithChildren = EditorRecipesRoute._addFileChildren(
  EditorRecipesRouteChildren,
)

interface EditorTabsRouteChildren {
  EditorTabsIdRoute: typeof EditorTabsIdRoute
}

const EditorTabsRouteChildren: EditorTabsRouteChildren = {
  EditorTabsIdRoute: EditorTabsIdRoute,
}

const EditorTabsRouteWithChildren = EditorTabsRoute._addFileChildren(
  EditorTabsRouteChildren,
)

interface EditorRouteChildren {
  EditorRecipesRoute: typeof EditorRecipesRouteWithChildren
  EditorTabsRoute: typeof EditorTabsRouteWithChildren
}

const EditorRouteChildren: EditorRouteChildren = {
  EditorRecipesRoute: EditorRecipesRouteWithChildren,
  EditorTabsRoute: EditorTabsRouteWithChildren,
}

const EditorRouteWithChildren =
  EditorRoute._addFileChildren(EditorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  EditorRoute: EditorRouteWithChildren,
  SearchRoute: SearchRoute,
  KindSlugRoute: KindSlugRoute,
  KindIndexRoute: KindIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
