/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as KindRouteImport } from './routes/$kind'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KindSlugRouteImport } from './routes/$kind.$slug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const KindRoute = KindRouteImport.update({
  id: '/$kind',
  path: '/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KindSlugRoute = KindSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KindRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$kind': typeof KindRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRoute
  '/search': typeof SearchRoute
  '/$kind/$slug': typeof KindSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$kind': typeof KindRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRoute
  '/search': typeof SearchRoute
  '/$kind/$slug': typeof KindSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$kind': typeof KindRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRoute
  '/search': typeof SearchRoute
  '/$kind/$slug': typeof KindSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$kind'
    | '/admin'
    | '/auth'
    | '/editor'
    | '/search'
    | '/$kind/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$kind'
    | '/admin'
    | '/auth'
    | '/editor'
    | '/search'
    | '/$kind/$slug'
  id:
    | '__root__'
    | '/'
    | '/$kind'
    | '/admin'
    | '/auth'
    | '/editor'
    | '/search'
    | '/$kind/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KindRoute: typeof KindRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  EditorRoute: typeof EditorRoute
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$kind': {
      id: '/$kind'
      path: '/$kind'
      fullPath: '/$kind'
      preLoaderRoute: typeof KindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$kind/$slug': {
      id: '/$kind/$slug'
      path: '/$slug'
      fullPath: '/$kind/$slug'
      preLoaderRoute: typeof KindSlugRouteImport
      parentRoute: typeof KindRoute
    }
  }
}

interface KindRouteChildren {
  KindSlugRoute: typeof KindSlugRoute
}

const KindRouteChildren: KindRouteChildren = {
  KindSlugRoute: KindSlugRoute,
}

const KindRouteWithChildren = KindRoute._addFileChildren(KindRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KindRoute: KindRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  EditorRoute: EditorRoute,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
