/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MapRouteImport } from './routes/map'
import { Route as KarteRouteImport } from './routes/karte'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorIndexRouteImport } from './routes/editor.index'
import { Route as KindIndexRouteImport } from './routes/$kind.index'
import { Route as AdminTrashRouteImport } from './routes/admin.trash'
import { Route as AdminBrokenLinksRouteImport } from './routes/admin.broken-links'
import { Route as KindSlugRouteImport } from './routes/$kind.$slug'
import { Route as EditorTabsIndexRouteImport } from './routes/editor.tabs.index'
import { Route as EditorRecipesIndexRouteImport } from './routes/editor.recipes.index'
import { Route as EditorTabsIdRouteImport } from './routes/editor.tabs.$id'
import { Route as EditorRecipesIdRouteImport } from './routes/editor.recipes.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const KarteRoute = KarteRouteImport.update({
  id: '/karte',
  path: '/karte',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EditorRoute,
} as any)
const KindIndexRoute = KindIndexRouteImport.update({
  id: '/$kind/',
  path: '/$kind/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrashRoute = AdminTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrokenLinksRoute = AdminBrokenLinksRouteImport.update({
  id: '/broken-links',
  path: '/broken-links',
  getParentRoute: () => AdminRoute,
} as any)
const KindSlugRoute = KindSlugRouteImport.update({
  id: '/$kind/$slug',
  path: '/$kind/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorTabsIndexRoute = EditorTabsIndexRouteImport.update({
  id: '/tabs/',
  path: '/tabs/',
  getParentRoute: () => EditorRoute,
} as any)
const EditorRecipesIndexRoute = EditorRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => EditorRoute,
} as any)
const EditorTabsIdRoute = EditorTabsIdRouteImport.update({
  id: '/tabs/$id',
  path: '/tabs/$id',
  getParentRoute: () => EditorRoute,
} as any)
const EditorRecipesIdRoute = EditorRecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => EditorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRouteWithChildren
  '/karte': typeof KarteRoute
  '/map': typeof MapRoute
  '/search': typeof SearchRoute
  '/$kind/$slug': typeof KindSlugRoute
  '/admin/broken-links': typeof AdminBrokenLinksRoute
  '/admin/trash': typeof AdminTrashRoute
  '/$kind/': typeof KindIndexRoute
  '/editor/': typeof EditorIndexRoute
  '/editor/recipes/$id': typeof EditorRecipesIdRoute
  '/editor/tabs/$id': typeof EditorTabsIdRoute
  '/editor/recipes/': typeof EditorRecipesIndexRoute
  '/editor/tabs/': typeof EditorTabsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/karte': typeof KarteRoute
  '/map': typeof MapRoute
  '/search': typeof SearchRoute
  '/$kind/$slug': typeof KindSlugRoute
  '/admin/broken-links': typeof AdminBrokenLinksRoute
  '/admin/trash': typeof AdminTrashRoute
  '/$kind': typeof KindIndexRoute
  '/editor': typeof EditorIndexRoute
  '/editor/recipes/$id': typeof EditorRecipesIdRoute
  '/editor/tabs/$id': typeof EditorTabsIdRoute
  '/editor/recipes': typeof EditorRecipesIndexRoute
  '/editor/tabs': typeof EditorTabsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRouteWithChildren
  '/karte': typeof KarteRoute
  '/map': typeof MapRoute
  '/search': typeof SearchRoute
  '/$kind/$slug': typeof KindSlugRoute
  '/admin/broken-links': typeof AdminBrokenLinksRoute
  '/admin/trash': typeof AdminTrashRoute
  '/$kind/': typeof KindIndexRoute
  '/editor/': typeof EditorIndexRoute
  '/editor/recipes/$id': typeof EditorRecipesIdRoute
  '/editor/tabs/$id': typeof EditorTabsIdRoute
  '/editor/recipes/': typeof EditorRecipesIndexRoute
  '/editor/tabs/': typeof EditorTabsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/editor'
    | '/karte'
    | '/map'
    | '/search'
    | '/$kind/$slug'
    | '/admin/broken-links'
    | '/admin/trash'
    | '/$kind/'
    | '/editor/'
    | '/editor/recipes/$id'
    | '/editor/tabs/$id'
    | '/editor/recipes/'
    | '/editor/tabs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/karte'
    | '/map'
    | '/search'
    | '/$kind/$slug'
    | '/admin/broken-links'
    | '/admin/trash'
    | '/$kind'
    | '/editor'
    | '/editor/recipes/$id'
    | '/editor/tabs/$id'
    | '/editor/recipes'
    | '/editor/tabs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/editor'
    | '/karte'
    | '/map'
    | '/search'
    | '/$kind/$slug'
    | '/admin/broken-links'
    | '/admin/trash'
    | '/$kind/'
    | '/editor/'
    | '/editor/recipes/$id'
    | '/editor/tabs/$id'
    | '/editor/recipes/'
    | '/editor/tabs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  EditorRoute: typeof EditorRouteWithChildren
  KarteRoute: typeof KarteRoute
  MapRoute: typeof MapRoute
  SearchRoute: typeof SearchRoute
  KindSlugRoute: typeof KindSlugRoute
  KindIndexRoute: typeof KindIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karte': {
      id: '/karte'
      path: '/karte'
      fullPath: '/karte'
      preLoaderRoute: typeof KarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/': {
      id: '/editor/'
      path: '/'
      fullPath: '/editor/'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof EditorRoute
    }
    '/$kind/': {
      id: '/$kind/'
      path: '/$kind'
      fullPath: '/$kind/'
      preLoaderRoute: typeof KindIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trash': {
      id: '/admin/trash'
      path: '/trash'
      fullPath: '/admin/trash'
      preLoaderRoute: typeof AdminTrashRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/broken-links': {
      id: '/admin/broken-links'
      path: '/broken-links'
      fullPath: '/admin/broken-links'
      preLoaderRoute: typeof AdminBrokenLinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$kind/$slug': {
      id: '/$kind/$slug'
      path: '/$kind/$slug'
      fullPath: '/$kind/$slug'
      preLoaderRoute: typeof KindSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/tabs/': {
      id: '/editor/tabs/'
      path: '/tabs'
      fullPath: '/editor/tabs/'
      preLoaderRoute: typeof EditorTabsIndexRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/recipes/': {
      id: '/editor/recipes/'
      path: '/recipes'
      fullPath: '/editor/recipes/'
      preLoaderRoute: typeof EditorRecipesIndexRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/tabs/$id': {
      id: '/editor/tabs/$id'
      path: '/tabs/$id'
      fullPath: '/editor/tabs/$id'
      preLoaderRoute: typeof EditorTabsIdRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/recipes/$id': {
      id: '/editor/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/editor/recipes/$id'
      preLoaderRoute: typeof EditorRecipesIdRouteImport
      parentRoute: typeof EditorRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBrokenLinksRoute: typeof AdminBrokenLinksRoute
  AdminTrashRoute: typeof AdminTrashRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBrokenLinksRoute: AdminBrokenLinksRoute,
  AdminTrashRoute: AdminTrashRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EditorRouteChildren {
  EditorIndexRoute: typeof EditorIndexRoute
  EditorRecipesIdRoute: typeof EditorRecipesIdRoute
  EditorTabsIdRoute: typeof EditorTabsIdRoute
  EditorRecipesIndexRoute: typeof EditorRecipesIndexRoute
  EditorTabsIndexRoute: typeof EditorTabsIndexRoute
}

const EditorRouteChildren: EditorRouteChildren = {
  EditorIndexRoute: EditorIndexRoute,
  EditorRecipesIdRoute: EditorRecipesIdRoute,
  EditorTabsIdRoute: EditorTabsIdRoute,
  EditorRecipesIndexRoute: EditorRecipesIndexRoute,
  EditorTabsIndexRoute: EditorTabsIndexRoute,
}

const EditorRouteWithChildren =
  EditorRoute._addFileChildren(EditorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  EditorRoute: EditorRouteWithChildren,
  KarteRoute: KarteRoute,
  MapRoute: MapRoute,
  SearchRoute: SearchRoute,
  KindSlugRoute: KindSlugRoute,
  KindIndexRoute: KindIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
